Left-on-Read/leftonread

- electron/package.json
- electron/src/app.global.css
- electron/src/chatBro/constants/stopWords.ts
- electron/src/chatBro/queries/WordOrEmoji/filters.ts
- electron/src/components/filters/ContactFilter.tsx
- electron/src/components/filters/GroupChatFilter.tsx
- electron/src/index.tsx
- electron/src/utils/initUtils/index.ts
- electron/yarn.lock
> [WIP] Global Contact Filter

- electron/.eslintrc.js
- electron/package.json
- electron/src/app.global.css
- electron/src/chatBro/constants/defaultFilters.ts
- electron/src/chatBro/constants/filters.ts
- electron/src/chatBro/constants/reactions.ts
- electron/src/chatBro/constants/stopWords.ts
- electron/src/chatBro/queries/TopFriends/TopFriends.ts
- electron/src/chatBro/queries/TopFriends/columns.ts
- electron/src/chatBro/queries/TopFriends/filters.ts
- electron/src/chatBro/queries/TopFriends/types.d.ts
- electron/src/chatBro/queries/WordOrEmoji/WordOrEmoji.ts
- electron/src/chatBro/queries/WordOrEmoji/columns.ts
- electron/src/chatBro/queries/WordOrEmoji/filters.ts
- electron/src/chatBro/queries/WordOrEmoji/types.d.ts
- electron/src/components/charts/TopFriendsChart.tsx
- electron/src/components/charts/WordOrEmojiCountChart.tsx
- electron/src/components/filters/ContactFilter.tsx
- electron/src/components/filters/GroupChatFilter.tsx
- electron/src/index.tsx
- electron/src/tables/ContactTable.ts
- electron/src/tables/Core/Count/index.ts
- electron/src/utils/initUtils/index.ts
- electron/yarn.lock
- Add filtering logic for contacts, group chat filtering
- Add OutputColumns to make it clear what columns can be referenced. 
Resolves #39
> Filtering for Contacts, Group Chat Filtering, and clean up Column types

- electron/.eslintrc.js
- electron/package.json
- electron/src/app.global.css
- electron/src/chatBro/constants/defaultFilters.ts
- electron/src/chatBro/constants/filters.ts
- electron/src/chatBro/constants/reactions.ts
- electron/src/chatBro/constants/stopWords.ts
- electron/src/chatBro/queries/TopFriends/TopFriends.ts
- electron/src/chatBro/queries/TopFriends/columns.ts
- electron/src/chatBro/queries/TopFriends/filters.ts
- electron/src/chatBro/queries/TopFriends/types.d.ts
- electron/src/chatBro/queries/WordOrEmoji/WordOrEmoji.ts
- electron/src/chatBro/queries/WordOrEmoji/columns.ts
- electron/src/chatBro/queries/WordOrEmoji/filters.ts
- electron/src/chatBro/queries/WordOrEmoji/types.d.ts
- electron/src/components/charts/TopFriendsChart.tsx
- electron/src/components/charts/WordOrEmojiCountChart.tsx
- electron/src/components/filters/ContactFilter.tsx
- electron/src/components/filters/GroupChatFilter.tsx
- electron/src/components/filters/LimitFilter.tsx
- electron/src/index.tsx
- electron/src/tables/ContactTable.ts
- electron/src/tables/Core/Count/index.ts
- electron/src/utils/initUtils/index.ts
- electron/yarn.lock
- Add filtering logic for contacts, group chat filtering
- Add OutputColumns to make it clear what columns can be referenced. 
Resolves #39  and https://github.com/Left-on-Read/app/issues/6
Note: I'm quite pleased the queries are extremely fast :)
> Contacts, Limits, Group Chat Filtering, and clean up Column types

- app/electron/package.json
- app/electron/yarn.lock
Resolves #64 — relying on workflows from now on.
> Remove husky

- .github/workflows/web-test.yml
- web/package.json
- web/src/components/sections/GetNotified.tsx
#60 I'm skipping out on an auto formatting workflow. I'm worried about the auto-formatting that your local version might get out of sync from what is expected from the remote version.
> Add web test workflow

- .github/workflows/app-format.yml
- .github/workflows/app-test.yml
- .github/workflows/server-test.yml
- .github/workflows/web-test.yml
Missed a spot when introducing `eslint-config`. Need to update when workflows are run.
> Fixing workflow dependencies

- README.md
- app/README.md
- server/README.md
- web/README.md
When I spoke with @jjanelee97 , these seemed to be her main concerns and questions.
@jjanelee97 mind reviewing, as your 2-week-old self would be the main consumer of this documentation? Thanks! 🙇🏼
> Update READMEs for future contributors

- app/README.md
@jjanelee97 — making your change requested here https://github.com/Left-on-Read/leftonread/pull/91#pullrequestreview-605892131
> Update README to reflect giving full disk access

- web/src/components/Button.tsx
- web/src/components/Input.tsx
- web/src/components/StatusLoader.tsx
- web/src/components/sections/GetNotified.tsx
- web/src/hooks/usePrevious.ts
- web/src/theme/index.ts
- web/src/theme/semantics.ts
Adding in some initial work on adding a loading and error state to the email sign up. It's not perfect quite yet, but it gets the job done. 
Could fixes:
- Adjust layout so that status is below input and button
- Add disabled css to input and button
> Adding loading and error states to email signup

- app/src/components/filters/ContactFilter.tsx
- app/src/index.tsx
- app/src/utils/initUtils/contacts/columns.ts
- app/src/utils/initUtils/contacts/index.ts
- app/src/utils/initUtils/contacts/types.d.ts
- app/src/utils/initUtils/index.ts
chore: give Contact Filter types
> Give Contact Filter types

- app/src/utils/initUtils/contacts/index.ts
Order contact filter results by count, then email, then no matches
> Order Contact Filter Options

- web/src/components/sections/GetStarted.tsx
- web/src/components/sections/Infographic.tsx
- web/src/theme/index.ts
> [web] Fix vertical responsiveness bug

- web/package.json
- web/src/components/sections/GetNotified.tsx
- web/src/pages/_app.tsx
- web/src/pages/_document.tsx
- web/src/utils/gtag.ts
- web/yarn.lock
> [web] Adding Google analytics

- web/README.md
- web/src/components/Footer.tsx
- web/src/components/sections/GetNotified.tsx
- web/src/components/sections/GetStarted.tsx
- web/src/pages/PrivacyPolicy.tsx
> Fix web footer

- web/jest.config.js
- web/package.json
- web/src/components/StatusLoader.tsx
- web/src/components/sections/GetNotified.tsx
- web/src/utils/validation.test.ts
- web/src/utils/validation.ts
- web/yarn.lock
Adding some basic email validation
> Adding basic email validation

- .github/workflows/web-test.yml
Starting to add unit tests to web, so we should make them blocking on PRs
> Run unit tests in web workflow

- app/src/addressBro/util/index.ts
- app/src/components/charts/TopFriendsChart.tsx
- app/src/components/charts/WordOrEmojiCountChart.tsx
- app/src/db/index.ts
- app/src/index.tsx
- app/src/tables/Core/Count/index.ts
- app/src/tables/index.ts
- app/src/utils/initUtils/index.ts
Resolves #38 
Logs will write, on macOS, to: `~/Library/Logs/{app name}/{process type}.log`
> Standardize Logging

- web/src/__tests__/footer.test.tsx
- web/src/components/Footer.tsx
- Add Vercel Logo and Link to Web Footer
- Add tests
> Add Vercel to Web Footer

- README.md
- web/README.md
Resolves https://github.com/Left-on-Read/leftonread/issues/142
> Trigger build with envs in Vercel + Update READMEs 

- web/src/components/Footer.tsx
- web/src/components/charts/data.ts
- web/src/theme/index.ts
> Clean up Footer + Text Constants Data 

- app/README.md
- docs: Update Troubleshooting on Memory Allocation error. Resolves #153
> docs: Update App Troubleshooting to Cover Memory Allocation Error

- app/src/chatBro/queries/TopFriends/filters.ts
- app/src/chatBro/queries/WordOrEmoji/filters.ts
[app] Filter out texts with less than length of 1
> [app] Filter out texts with less than length of 1

- app/src/chatBro/queries/TopFriends/TopFriends.ts
- [app] Hotfix: fix that sent and received was flipped
> [app] Hotfix: fix that sent and received was flipped

- app/src/main.dev.ts
- app/yarn.lock
Add electron-util to help with adding full disk access
> [app] Add electron-util

- app/package.json
- app/src/components/App.tsx
- app/src/components/Dashboard.tsx
- app/src/utils/initUtils/constants/directories.ts
- app/src/utils/initUtils/index.ts
- app/yarn.lock
Prompt user to open system preferences if it appears that they don't have full disk access. Resolves #92 
Still a lot of work to be done here, such as making it pretty, adding some better text, and cleaning up the component in general.
> [app] Basic button to prompt opening system preferences for Full Disk Access

- app/src/components/App.tsx
- [app] Hotfix disk access
This now works on prod in a real packaged app
:
> [app] Hotfix disk access

- app/package.json
- app/src/components/App.tsx
- app/src/custom.d.ts
- app/src/main.dev.ts
- app/src/utils/analytics.ts
- app/src/utils/index.ts
- app/src/utils/store.ts
- app/tsconfig.json
- app/yarn.lock
> [app] Adding Google analytics

- app/README.md
- app/package.json
- app/src/chatBro/constants/filters.ts
- app/src/utils/initUtils/constants/directories.ts
- app/src/utils/initUtils/index.ts
- [app] Add start:debug script and remove rm recommendation from docs.
> [app] Add start:debug script and remove rm recommendation from docs.

- app/src/components/App.tsx
- app/src/components/pages/AccessPage.tsx
> [app] Add basic routing set up to App

- app/src/chatBro/queries/TopFriends/TopFriends.ts
- app/src/chatBro/queries/TopFriends/filters.ts
- app/src/components/Dashboard.tsx
- app/src/components/filters/ContactFilter.tsx
- app/src/tables/Core/Count/index.ts
- app/src/utils/initUtils/contacts/index.ts
> [app] Add joins to chat_message_join and chat_handle_join in all tables in init

- app/src/chatBro/queries/TopFriends/TopFriends.ts
- app/src/chatBro/queries/WordOrEmoji/WordOrEmoji.ts
- app/src/chatBro/queries/WordOrEmoji/columns.ts
- app/src/tables/Chat/Count/index.ts
- app/src/tables/Core/Main/index.ts
- app/src/tables/definitions.ts
- app/src/tables/index.ts
- app/src/utils/initUtils/contacts/index.ts
- app/src/utils/initUtils/index.ts
Create Core Main table to optimize subsequent  querying
> [app] Create Core Main table to optimize subsequent querying

- .vscode/settings.json
- app/package.json
- app/src/components/App.tsx
- app/src/components/design/Button.tsx
- app/src/components/pages/GetStartedPage.tsx
- app/src/index.html
- app/src/utils/store.ts
- app/yarn.lock
Starting the `Getting Started` page to request for accepting privacy policy. Also the beginnings of a shared component library for the app.
> [app] Core functionality on getting started page

- app/.eslintignore
Accidentally deleted the eslint ignore
> Add back in eslint ignore

- app/src/components/Dashboard/Navbar.tsx
- app/src/components/Initializer.tsx
> Fix layering

- app/src/components/App.tsx
- app/src/components/Home/Redirecter.tsx
- app/src/main/ipcListeners.ts
> Redirect to dashboard if already initialized

- app/src/components/App.tsx
- app/src/components/Dashboard/Dashboard.tsx
- app/src/components/Dashboard/Navbar.tsx
> Implement refresh button

- .vscode/settings.json
- app/src/analysis/queries/TextsOverTimeQuery.ts
- app/src/analysis/queries/TopFriendsQuery.ts
- app/src/analysis/queries/TotalSentVsReceivedQuery.ts
- app/src/analysis/queries/filters/sharedQueryFilters.ts
- app/src/components/Graphs/SentVsReceivedChart.tsx
- app/src/components/Graphs/TopFriendsChart.tsx
- app/src/components/Graphs/WordOrEmojiCountChart.tsx
- app/src/constants/filters.ts
- app/src/main/ipcListeners.ts
Filters were copy pasted in each file, but they are the same. 
Also start texts over time query.
> Move filters to shared type & start texts over time query

- app/src/components/Home/GetStarted.tsx
- app/src/main/ipcListeners.ts
Using `fs.access` instead of trying to copy a file. Had trouble with a packaged build using the copy file method.
> Update permissions check

- app/src/analysis/initializeCoreDb.ts
- app/src/analysis/queries/TextsOverTimeQuery.ts
- app/src/analysis/queries/filters/sharedQueryFilters.ts
- app/src/analysis/tables/CalendarTable.ts
- app/src/analysis/tables/ChatTable.ts
- app/src/analysis/tables/ContactTable.ts
- app/src/analysis/tables/types.ts
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Graphs/TextsOverTimeChart.tsx
- app/src/main/ipcListeners.ts
> Number of Texts Per Day (Texts Over Time)

- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Graphs/SentVsReceivedChart.tsx
- app/src/components/Graphs/TextsOverTimeChart.tsx
- app/src/components/Graphs/TopFriendsChart.tsx
- app/src/components/Graphs/WordOrEmojiCountChart.tsx
Adding some sort of loading & error states to graphs
Closes #229 #217
> Update loading states of graphs

- app/src/analysis/queries/TotalSentVsReceivedQuery.ts
- app/src/analysis/queries/WordOrEmojiQuery.ts
- app/src/analysis/queries/filters/sharedQueryFilters.ts
- app/src/analysis/tables/ChatTable.ts
- app/src/analysis/tables/CoreTable.ts
- app/src/constants/emojis.ts
- Added fluff filter on core main table
- Fixed that getEmojiData is not async
> Fixed incorrect received/sent count due to no fluff filter on core table AND group by GUID to fix group chat counts

- app/src/analysis/queries/WordOrEmojiQuery.ts
- app/src/analysis/tables/ContactTable.ts
> Remove punctuation from words 

- app/release/app/package.json
- app/src/components/Dashboard/Navbar.tsx
- app/src/components/Home/GetStarted.tsx
- app/src/constants/versions.ts
- app/src/main/ipcListeners.ts
Adding a button that wipes `.leftonread` folder and sends user back to the beginning
> Add in a hard reset button

- app/src/components/Graphs/TextsOverTimeChart.tsx
Smoothing out the numer of messages per day chart
Closes #236
> Sample logic for TOT

- app/package.json
- app/src/analysis/queries/TimeOfDayQuery.ts
- app/src/components/App.css
- app/src/components/App.tsx
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Graphs/TimeOfDayChart.tsx
- app/src/main/ipcListeners.ts
- app/yarn.lock
> Messages per Time of day chart

- app/src/analysis/initializeCoreDb.ts
- app/src/main/ipcListeners.ts
Should resolve issues with refreshing
#260
> Wipe LOR folder on init

- app/src/analysis/queries/filters/sharedQueryFilters.ts
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Dashboard/Dashboard.tsx
- app/src/components/Dashboard/Navbar.tsx
- app/src/components/Filters/FilterPanel.tsx
- app/src/components/Graphs/TextsOverTimeChart.tsx
- app/src/components/Graphs/TopFriendsChart.tsx
- app/src/constants/filters.ts
Need to update some loading states, but this gets functionality into place
Closes #247
> Add a time range filter option

- app/src/components/App.tsx
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Dashboard/Dashboard.tsx
- app/src/components/Dashboard/Navbar.tsx
- app/src/components/Filters/FilterPanel.tsx
- app/src/components/Graphs/SentVsReceivedChart.tsx
- app/src/components/Graphs/TextsOverTimeChart.tsx
- app/src/components/Graphs/TimeOfDayChart.tsx
- app/src/components/Graphs/TopFriendsChart.tsx
- app/src/components/Graphs/WordOrEmojiCountChart.tsx
- app/src/components/Initializer.tsx
This fixes some rendering issues of load happening twice, and also updates the loading UI so graphs don't jump around as much
> Update Loading State and excessive loading with Filters

- app/src/components/App.tsx
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Dashboard/Dashboard.tsx
- app/src/components/Dashboard/GlobalContext.tsx
- app/src/components/Dashboard/Navbar.tsx
- app/src/components/Filters/FilterPanel.tsx
- app/src/components/Graphs/SentVsReceivedChart.tsx
- app/src/components/Graphs/TopFriendsChart.tsx
- app/src/components/Graphs/WordOrEmojiCountChart.tsx
- app/src/components/Initializer.tsx
Adding global context to manage contacts and time range that needs to be fetched AFTER the dashboard has loaded so introduces some tricky state...
also fixing bad bug that caused things to re-query anytime ANYTHING re-rendered....
> Add Global Context

- app/package.json
- app/src/analysis/initializeCoreDb.ts
- app/src/analysis/queries/RawMessageQuery.ts
- app/src/analysis/queries/TimeOfDayQuery.ts
- app/src/analysis/queries/TotalSentimentQuery.ts
- app/src/analysis/tables/CoreTable.ts
- app/src/analysis/tables/SentimentTable.ts
- app/src/analysis/tables/types.ts
- app/src/components/App.css
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Dashboard/Navbar.tsx
- app/src/components/Graphs/TotalSentimentChart.tsx
- app/src/main/ipcListeners.ts
- app/yarn.lock
This adds in:
* Sentiment Table
* Sentiment Tab
* Initial Sentiment query of overall breakdown
> Adding in Sentiment tab

- app/src/analysis/queries/RawMessageQuery.ts
- app/src/analysis/queries/SentimentOverTimeQuery.ts
- app/src/analysis/queries/TopSentimentFriendsQuery.ts
- app/src/analysis/queries/TotalSentimentQuery.ts
- app/src/analysis/tables/SentimentTable.ts
- app/src/components/App.css
- app/src/components/ComingSoon.tsx
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Dashboard/Navbar.tsx
- app/src/components/Graphs/SentimentOverTimeChart.tsx
- app/src/components/Graphs/TopSentimentFriendsChart.tsx
- app/src/components/Graphs/TotalSentimentChart.tsx
- app/src/main/ipcListeners.ts
> Adding in Sentiment over time and Most Positive Conversations

- app/package.json
- app/src/components/Dashboard/Dashboard.tsx
- app/src/components/Initializer.tsx
- app/src/main/ipcListeners.ts
- app/src/utils/store.ts
This way we can force people to refresh their data
> Adding migration logic

- app/release.js
fetch with all flag and make error message more clear that it might be local changes
> Minor release script changes

- app/src/components/Dashboard/GroupChatTab.tsx
- app/src/components/Graphs/TextsOverTimeChart.tsx
Not sure exactly what this issue is, but this seems to fix it
> Fix Sampling

- app/src/components/Dashboard/Dashboard.tsx
- app/src/components/Dashboard/GroupChatTab.tsx
- app/src/components/Graphs/TimeOfDayChart.tsx
- app/src/components/Premium/PremiumModal.tsx
* Fix group chat select bug
* Improve UI on group chat select
* Update group chat icons
* Fix time of day missing data points bug
> Small Improvements

- app/src/main/menu.ts
* Cleaning up the options in the menu
> Cleaning up menu

- app/src/components/Graphs/GraphContainer.tsx
> Fix button styling

- app/src/components/Graphs/GraphContainer.tsx
- app/src/components/Graphs/GroupChats/GroupChatActivityOverTimeChart.tsx
- app/src/components/Graphs/GroupChats/GroupChatByFriendsChart.tsx
- app/src/components/Graphs/SentimentOverTimeChart.tsx
- app/src/components/Graphs/TextsOverTimeChart.tsx
- app/src/components/Graphs/TopFriendsChart.tsx
- app/src/components/Graphs/TopSentimentFriendsChart.tsx
- app/src/components/Graphs/WordOrEmojiCountChart.tsx
* Fixing loading & error graph states
> UI Touch ups

- app/src/components/Productivity/MessageSchedulerModal.tsx
Closes #366 
Cleans up UI, makes the select searchable
> Update select for scheduled messages

- server/package.json
- server/src/controllers/PremiumController.ts
- server/yarn.lock
Maintaining subscription + cancellation logic
> Additional server logic

- app/src/components/Graphs/TopSentimentFriendsChart.tsx
> Fix percentage bug

- README.md
404ed when I first tried to download a release!
> Fix Releases link in README

- app/src/components/Pages/SettingsPage.tsx
- app/src/components/Premium/UnlockPremiumButton.tsx
> Update premium button

- app/src/analysis/queries/filters/sharedQueryFilters.ts
- app/src/components/Dashboard/AnalyticsPage.tsx
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Graphs/WordOrEmojiCountChart.tsx
- app/src/components/Premium/PremiumModal.tsx
> Filter by a word or emoji

- app/src/analysis/queries/InboxReadQuery.ts
> Limit Inbox to last 3 months.

- app/src/components/Filters/FilterPanel.tsx
- app/src/components/Premium/UnlockPremiumButton.tsx
> Update filtering preview

- app/src/analysis/queries/GroupChats/GroupChatByFriendsQuery.ts
- app/src/analysis/queries/WrappedQueries/FunniestMessageQuery.ts
- app/src/components/Dashboard/GroupChatTab.tsx
- app/src/components/Dashboard/Wrapped/Sections/FunniestMessage.tsx
- app/src/components/Dashboard/Wrapped/WrappedPage.tsx
- app/src/components/Graphs/GroupChats/GroupChatFunniestMessage.tsx
- app/src/main/ipcListeners.ts
> Funniest Message on Group Chat Tab

- app/src/analysis/queries/FriendsOverTimeQuery.ts
- app/src/components/Dashboard/ChartTabs.tsx
- app/src/components/Dashboard/GlobalContext.tsx
- app/src/components/Filters/FilterPanel.tsx
- app/src/components/Graphs/FriendsOverTimeChart.tsx
- app/src/components/Productivity/MessageSchedulerModal.tsx
- app/src/main/ipcListeners.ts
> Friends Over Time

- app/src/analysis/queries/WordOrEmojiQuery.ts
- app/src/analysis/queries/WrappedQueries/FunniestMessageQuery.ts
- app/src/analysis/queries/filters/sharedQueryFilters.ts
- app/src/components/Dashboard/Wrapped/WrappedPage.tsx
- app/src/components/Graphs/GroupChats/GroupChatByFriendsChart.tsx
- app/src/components/Home/GetStarted.tsx
- app/src/components/Home/Home.tsx
- app/src/constants/filters.ts
> Fix timeRange filter not working on wrapped sections

- app/src/components/Dashboard/Wrapped/WrappedGradient.tsx
closes https://github.com/Left-on-Read/leftonread/issues/453
> perf: optimize WrappedGradient

- app/src/components/Home/GetStarted.tsx
- app/src/main/ipcListeners.ts
Reverts Left-on-Read/leftonread#472
> Revert "🐛: fix check permissions hanging for some users by unpromisifying it"

- app/src/analysis/queries/WrappedQueries/TopFriendsSimpleQuery.ts
- app/src/components/Home/GetStarted.tsx
- app/src/main/ipcListeners.ts
- app/src/utils/store.ts
so that thread is not blocked 
----
Basically improved version of #472 which was reverted because it a published version it did not work
> Change check permissions to use async method instead
